### ISSUE TITLE
Can not run under the Odoo

### ISSUE THREAD

**Issue by nimaam** [ambientWave/Odoo-Dental-Clinic-Managment-System-With-REST-API#1]
This code is not running under the Odoo 16 and 17, could you please help to install.

**Comment by ambientWave** [comment]
Dear @nimaam

The whole module was developed for Odoo 14

**Comment by acostarojo** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\web\controllers\main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\web\controllers\main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\api.py", line 404, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\api.py", line 391, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-73>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\base\models\ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\base\models\ir_module.py", line 454, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\addons\base\models\ir_module.py", line 572, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\modules\loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\modules\loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\tools\convert.py", line 729, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\tools\convert.py", line 775, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20231205\server\odoo\http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: Fallo en la carga del módulo Dental_Clinic_Managment_System_With_REST_API: no se pudo procesar el archivo Dental_Clinic_Managment_System_With_REST_API\security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_appointment' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_appointment' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_appointment' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_dental_procedure_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_dental_procedure_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_dental_procedure_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_patient' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_patient' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_patient' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_clinic_doctor' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_clinic_doctor' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_clinic_doctor' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_appointment_attachment_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_appointment_attachment_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_appointment_attachment_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_patient_prescription_line' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_api_access_token' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_api_access_token' en el campo 'Model'
No se han encontrado registros coincidentes para id. externo 'dental_clinic.model_api_access_token' en el campo 'Model'
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Falta el valor requerido para el campo 'Model' (model_id)
Se encontraron más de 10 errores y más de un error por cada 10 segundos, se pausó para evitar mostrar varios errores.

**Comment by Atifsa1** [comment]
Even with V14 version... its showing error.
------------------------------------------------------------
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/cloudclusters/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/cloudclusters/odoo/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/cloudclusters/odoo/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1374, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 404, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 391, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 454, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 572, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 729, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 775, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/cloudclusters/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: Module loading Odoo-Dental-Clinic-Managment-System-With-REST-API-main failed: file Odoo-Dental-Clinic-Managment-System-With-REST-API-main/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'dental_clinic.model_patient_appointment' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_appointment' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_appointment' in field 'Model'
No matching record found for external id 'dental_clinic.model_dental_procedure_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_dental_procedure_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_dental_procedure_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_patient' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_patient' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_patient' in field 'Model'
No matching record found for external id 'dental_clinic.model_clinic_doctor' in field 'Model'
No matching record found for external id 'dental_clinic.model_clinic_doctor' in field 'Model'
No matching record found for external id 'dental_clinic.model_clinic_doctor' in field 'Model'
No matching record found for external id 'dental_clinic.model_appointment_attachment_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_appointment_attachment_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_appointment_attachment_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_patient_prescription_line' in field 'Model'
No matching record found for external id 'dental_clinic.model_api_access_token' in field 'Model'
No matching record found for external id 'dental_clinic.model_api_access_token' in field 'Model'
No matching record found for external id 'dental_clinic.model_api_access_token' in field 'Model'
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id)
Found more than 10 errors and more than one error per 10 records, interrupted to avoid showing too many errors.

**Comment by ambientWave** [comment]
Dear @Atifsa1 and @acostarojo,

You should put all content of this repository in a directory called dental_clinic

Best Regards

**Comment by ambientWave** [comment]
Dear @Atifsa1 and @acostarojo,

You should put all content of this repository in a directory called dental_clinic

In this case, directory tree will be something like this:

dental_clinic/
├── controllers
├── data
├── models
├── security
├── static
├── views
├── init.py
└── manifest.py

Best Regards

**Comment by ambientWave** [comment]
Dear @Atifsa1 and @acostarojo,

You should put all content of this repository in a directory called dental_clinic

In this case, directory tree will be something like this:

dental_clinic/
├── controllers
├── data
├── models
├── security
├── static
├── views
├── init.py
└── manifest.py

Best Regards
